steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    
  # Membuat image Docker dengan nama projek_akhir
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/projek_akhir", "."]

  # Push image ke Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/projek_akhir"]

  # Deploy ke Cloud Run dengan nama service projek_akhir
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "projek_akhir",
        "--image",
        "gcr.io/$PROJECT_ID/projek_akhir",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya disimpan di Google Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY